config/routes.rb
Rails.application.routes.draw do
  root to: 'pets#index'
  resources :pets do
    collection do
      get :adopted
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true, length: { minimum: 2 }
  validates :category, presence: true
  validates :birth, presence: true

  before_validation :capitalize

  def capitalize
    name.capitalize!
    category.capitalize!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.where(adoption: false)
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to root_path, notice: 'Add sucess!'
    else
      redirect_to new_pet_path, alert: 'Invalid Pet'
    end
  end

  def edit
  end

  def update
    @pet.update(pet_params)
    if @pet.update(pet_params)
      redirect_to root_path, notice: 'Update sucess!'
    else
      redirect_to edit_pet_path, alert: 'Invalid Pet!'
    end
  end

  def destroy
    @pet.destroy
    redirect_to root_path
  end

  def adopted
    @pets = Pet.where(adoption: true)
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :category, :birth, :adoption)
  end

  def set_pet
    @pet = Pet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetsAdoption</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/flashes"%>
    <%= render "shared/navbar" %>
    <div class = "container mt-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pets/adopted.html.erb
<div class="conteiner">
  <div class="d-flex justify-content-center">
    <h1 class="mt-4 border-bottom"><strong> Pets Adopteds </strong></h1>
  </div>
  <div class="d-flex align-content-start flex-wrap">
    <% @pets.each do |pet| %>
      <div class="col-4 mb-3">
        <div class="card" style="width: 18rem;">
          <img src="..." class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title border-bottom"><%= pet.name %></h5>
            <p class="card-text">Category: <%= pet.category %></p>
            <p class="card-text">Birth: <%= pet.birth %></p>
            <p> <%= link_to "Pet's details", pet_path(pet), class: "btn btn-primary" %></p>
            <p><%= link_to "Remove", pet_path(pet), class: "btn btn-outline-danger btn-sm", method: :delete, data: { confirm: "Are you sure?" } %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pets/edit.html.erb
<h1>Edit</h1>

<%= simple_form_for(@pet) do |f| %>
  <%= f.input :name %>
  <%= f.input :category %>
  <%= f.input :birth %>
  <%= f.input :adoption %>
  <%= f.submit %>
<% end %>

app/views/pets/index.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
    <h1 class="mt-4 border-bottom"><strong> Pets Availables </strong></h1>
  </div>
  <div class="d-flex align-content-start flex-wrap">
    <% @pets.each do |pet| %>
      <div class="col-4 mb-3">
        <div class="card" style="width: 18rem;">
          <img src="..." class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title border-bottom"><%= pet.name %></h5>
            <p class="card-text">Category: <%= pet.category %></p>
            <p class="card-text">Birth: <%= pet.birth %></p>
            <p> <%= link_to "Pet's details", pet_path(pet), class: "btn btn-primary" %></p>
            <p><%= link_to "Remove", pet_path(pet), class: "btn btn-outline-danger btn-sm", method: :delete, data: { confirm: "Are you sure?" } %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= simple_form_for(@pet) do |f| %>
  <%= f.input :name, placeholder: "Minimun 2 letters" %>
  <%= f.input :category, placeholder: "Dog, Cat or Other" %>
  <%= f.input :birth %>
  <%= f.submit %>
<% end %>

app/views/pets/show.html.erb
<div class="d-flex justify-content-center">
  <h1 class="mt-4 border-bottom"><strong> Pet's Details </strong></h1>
</div>


<h2><%= @pet.name %></h2>
<p><%= @pet.category %></p>
<p><%= @pet.birth %></p>

<p><%= link_to "Edit", edit_pet_path(@pet), class: "btn btn-outline-secondary btn-sm" %></p>

<p><%= link_to "Remove", pet_path(@pet), class: "btn btn-outline-danger btn-sm", method: :delete, data: { confirm: "Are you sure?" }   %></p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer">
    <div class="footer-links">
      <a href="https://github.com/RaphaRCruz">
        <i class="fab fa-github">
          ::before
        </i>
      </a>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Pets", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>
      <div class="d-flex justify-content-between">
        <ul class="navbar-nav me-auto d-flex">
          <li class="pr-3 nav-item">
            <%= link_to "Add a Pet", new_pet_path, class: "nav-link" %>
          </li>
          <li class="pr-3 nav-item">
            <%= link_to "Adoptions", adopted_pets_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>